use crate::{binary::*, szs};
pub mod flags;
use flags::*;

pub struct Kcl {
    pub header: Header,
    pub pos_vectors: Vec<Vec3>,
    pub normals: Vec<Vec3>,
    pub prisms: Vec<Prism>,
    pub octree: Vec<u8>,
}

pub struct Header {
    pub pos_data_offset: u32,
    pub nrm_data_offset: u32,
    pub prism_data_offset: u32,
    pub block_data_offset: u32,
    pub prism_thickness: f32,
    pub area_min_pos: Vec3,
    pub area_x_width_mask: u32,
    pub area_y_width_mask: u32,
    pub area_z_width_mask: u32,
    pub block_width_shift: u32,
    pub area_x_blocks_shift: u32,
    pub area_xy_blocks_shift: u32,
    pub sphere_radius: f32,
}

pub struct Prism {
    pub height: f32,
    pub pos_idx: u16,
    pub fnrm_idx: u16,
    pub enrm1_idx: u16,
    pub enrm2_idx: u16,
    pub enrm3_idx: u16,
    pub flag: Flag,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Triangle {
    pub a: Vec3,
    pub b: Vec3,
    pub c: Vec3,
}

impl Prism {
    pub fn parse(data: &[u8], off: usize) -> Result<Self, String> {
        Ok(Self {
            height: read(data, off)?,
            pos_idx: read(data, off + 0x4)?,
            fnrm_idx: read(data, off + 0x6)?,
            enrm1_idx: read(data, off + 0x8)?,
            enrm2_idx: read(data, off + 0xa)?,
            enrm3_idx: read(data, off + 0xc)?,
            flag: Flag::from_u16(read(data, off + 0xe)?),
        })
    }

    pub fn build(&self, pos_buf: &[Vec3], nrm_buf: &[Vec3]) -> Option<Triangle> {
        let pos = *pos_buf.get(self.pos_idx as usize)?;
        let fnrm = *nrm_buf.get(self.fnrm_idx as usize)?;
        let enrm1 = *nrm_buf.get(self.enrm1_idx as usize)?;
        let enrm2 = *nrm_buf.get(self.enrm2_idx as usize)?;
        let enrm3 = *nrm_buf.get(self.enrm3_idx as usize)?;

        let cross_a = enrm1.cross(fnrm);
        let cross_b = enrm2.cross(fnrm);
        let denominator_a = cross_a.dot(enrm3);
        let denominator_b = cross_b.dot(enrm3);

        let v1 = pos;
        let v2 = pos + cross_b * (self.height / denominator_b);
        let v3 = pos + cross_a * (self.height / denominator_a);

        Some(Triangle { a: v1, b: v2, c: v3 })
    }
}

impl Header {
    pub fn parse(data: &[u8]) -> Result<Self, String> {
        Ok(Self {
            pos_data_offset: read(data, 0x0)?,
            nrm_data_offset: read(data, 0x4)?,
            prism_data_offset: read(data, 0x8)?,
            block_data_offset: read(data, 0xc)?,
            prism_thickness: read(data, 0x10)?,
            area_min_pos: read(data, 0x14)?,
            area_x_width_mask: read(data, 0x20)?,
            area_y_width_mask: read(data, 0x24)?,
            area_z_width_mask: read(data, 0x28)?,
            block_width_shift: read(data, 0x2c)?,
            area_x_blocks_shift: read(data, 0x30)?,
            area_xy_blocks_shift: read(data, 0x34)?,
            sphere_radius: read(data, 0x38)?,
        })
    }
}

impl Kcl {
    pub fn parse_raw(data: &[u8]) -> Result<Self, String> {
        let header = Header::parse(data)?;

        let pos_start = header.pos_data_offset as usize;
        let nrm_start = header.nrm_data_offset as usize;
        let prism_start = (header.prism_data_offset as usize)
            .checked_add(0x10)
            .ok_or("KCL prism offset overflow")?;
        let block_start = header.block_data_offset as usize;

        if pos_start < 0x10
            || pos_start > nrm_start
            || nrm_start > prism_start
            || prism_start > block_start
            || block_start > data.len()
        {
            return Err("KCL section offsets are invalid or outside the file".into());
        }
        if (nrm_start - pos_start) % 12 != 0
            || (prism_start - nrm_start) % 12 != 0
            || (block_start - prism_start) % 16 != 0
        {
            return Err("KCL section sizes are not aligned to their record sizes".into());
        }

        let pos_vectors = Vec3::section(data, pos_start, nrm_start)?;
        let normals = Vec3::section(data, nrm_start, prism_start)?;

        let mut prisms = Vec::with_capacity((block_start - prism_start) / 16);
        let mut offset = prism_start;
        while offset < block_start {
            prisms.push(Prism::parse(data, offset)?);
            offset += 16;
        }

        let octree = data[block_start..].to_vec();

        Ok(Self { header, pos_vectors, normals, prisms, octree })
    }

    pub fn to_obj(&self) -> String {
        let mut out = String::new();
        let mut n = 0usize;

        out += "# Generated by szs-utils\n";

        for prism in &self.prisms {
            let Some(tri) = prism.build(&self.pos_vectors, &self.normals) else {
                continue;
            };
            for v in [tri.a, tri.b, tri.c] {
                out += &format!("v {} {} {}\n", v.x, v.y, v.z);
            }
            let base = n * 3 + 1;
            out += &format!("f {} {} {}\n", base, base + 1, base + 2);
            n += 1;
        }
        out
    }

    pub fn from_szs(path: &str) -> Result<Self, String> {
        let szs = szs::parse(path)?;
        let kcl = szs.root.find("course.kcl").ok_or("course.kcl not found in SZS")?;
        let data = kcl.data.as_slice();
        Self::parse_raw(data)
    }
}